name: isolationhero
description: A new Flutter project.
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.2
    provider_architecture: ^1.0.3
    responsive_builder: ^0.1.4
    provider: ^3.2.0
    logger: ^0.7.0+2
    get_it: ^3.0.3
    equatable: ^1.0.1
    introduction_screen: ^1.0.8
    avatar_glow: ^1.1.0
    font_awesome_flutter: ^8.7.0
    flutter_map: ^0.8.2
    latlong: ^0.6.1
    positioned_tap_detector: ^1.0.2
    transparent_image: ^1.0.0
    geolocator: ^5.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true

    assets:
        - assets/

    fonts:
    - family: Monte
      fonts:
      - asset: assets/fonts/Monte-Black.ttf
      - asset: assets/fonts/Monte-Bold.ttf
      - asset: assets/fonts/Monte-Light.ttf
      - asset: assets/fonts/Monte-Regular.ttf
